# Generated by Django 4.0.1 on 2022-01-10 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0001_initial'),
        ('ulice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=60)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last_login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('userlastname', models.CharField(max_length=60)),
                ('telefon', models.CharField(max_length=22)),
                ('kucni_broj', models.PositiveIntegerField()),
                ('rola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.rola')),
                ('ulica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ulice.ulica')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
