# Generated by Django 4.0.1 on 2022-01-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnici', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kucni_broj',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefon',
            field=models.CharField(default=None, max_length=22, null=True),
        ),
    ]
