# Generated by Django 4.0.1 on 2022-01-14 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ulice', '0001_initial'),
        ('role', '0001_initial'),
        ('korisnici', '0002_alter_user_kucni_broj_alter_user_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rola',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.rola'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ulica',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ulice.ulica'),
        ),
    ]
