# Generated by Django 4.0.1 on 2022-01-10 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prikljucci', '0001_initial'),
        ('cjenovnik', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Racun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brojilo', models.DecimalField(decimal_places=3, max_digits=11)),
                ('potrosnja', models.DecimalField(decimal_places=3, max_digits=11)),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dug', models.DecimalField(decimal_places=2, max_digits=6)),
                ('on_hold', models.BooleanField(default=True)),
                ('placeno', models.BooleanField(default=False)),
                ('cjenovnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cjenovnik.cjenovnik')),
                ('popisivac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prikljucak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prikljucci.prikljucak')),
            ],
        ),
    ]
