# Generated by Django 4.0.1 on 2022-02-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racuni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='racun',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='racun',
            name='datum_dospijeca',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='racun',
            name='datum_placanja',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='racun',
            name='mjesec',
            field=models.CharField(default=None, max_length=8),
        ),
    ]
