# Generated by Django 4.0.1 on 2022-02-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racuni', '0002_racun_date_created_racun_datum_dospijeca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racun',
            name='datum_dospijeca',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='racun',
            name='datum_placanja',
            field=models.DateField(blank=True, default=None),
        ),
    ]
