# Generated by Django 4.0.1 on 2022-02-10 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiketi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiket',
            old_name='racunovodja',
            new_name='korisnik',
        ),
        migrations.RenameField(
            model_name='tiket',
            old_name='pitanje',
            new_name='opis_kvara',
        ),
        migrations.RemoveField(
            model_name='tiket',
            name='odgovor',
        ),
        migrations.RemoveField(
            model_name='tiket',
            name='prikljucak',
        ),
    ]
