# Generated by Django 4.0.1 on 2022-01-10 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prikljucci', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokumenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zahtjev', models.CharField(max_length=150)),
                ('zk_izvadak', models.CharField(max_length=150)),
                ('katastarski_plan', models.CharField(max_length=150)),
                ('prikljucak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prikljucci.prikljucak')),
            ],
        ),
    ]
