# Generated by Django 4.0.1 on 2022-02-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumenti_ugovora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenti',
            name='katastarski_plan',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='dokumenti',
            name='zahtjev',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='dokumenti',
            name='zk_izvadak',
            field=models.FileField(upload_to=''),
        ),
    ]
