# Generated by Django 4.0.1 on 2022-01-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MjesecnaUkupnaPotrosnja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mjesec', models.CharField(max_length=15)),
                ('volumen', models.DecimalField(decimal_places=3, max_digits=15)),
            ],
        ),
    ]
